language: python
dist: xenial
python:
  - 3.6
  - 3.7
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script: cp config.yaml.sample config.yaml
script: make test
#
# The travis configuration beloy will deploy this lambda to the function defined
# in your config.yaml file. This behavior can be defined for any of the
# development/qa/production environments.
#
# after_success:
#  - ENVIRONMENT_NAME=$TRAVIS_BRANCH
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then ENVIRONMENT_NAME=production; fi
# deploy:
#  - provider: script
#    skip_cleanup: true
#    script: "make deploy ENV=$ENVIRONMENT_NAME"
#    on:
#      branch: development
#
# If you are deploying an NYPL Lambda, see the engineering documentation in
# github for instructions on adding encrypted variables to you travis scripts
